### ISSUE TITLE
Linux: Can not start the Editor

### ISSUE THREAD

**Issue by chrisMa68** [supertuxkart/stk-editor#13]
Hello,
im compiled the editor under ubuntu 14.04. I try to start an I got the follow message:
Could not create archive for: textures
Could not create archive for: /home/chris/stk/stk-editor-master/build/lib/textures
Could not create archive for: /home/chris/stk/stk-editor-master/build/lib/textures
Could not create archive for: /home/chris/stk/stk-editor-master/build/lib/textures

If I use the 0.9.1 & 0.9. binarys form ( http://supertuxkart.sourceforge.net/) I got the same message /failture.
Has anyone what i can do ?

**Comment by deveee** [comment]
When you start stk-editor, you need to select the path to supertuxkart data directory. I'm not sure if it just needs stk-assets directory or if it needs whole data directory. Try to select data directory from STK 0.9.1.

**Comment by chrisMa68** [comment]
Thank you for your answer and it works. :-)

**Comment by chrisMa68** [comment]
Maybe you can add this Information on the Start Page.
