### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by Boyquotes** [supertuxkart/stk-editor#17]
A lot of image are not found and are not in this repository, where are they ?
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/grid-on_align-off.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/grid-plus.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/grid-minus.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/points-plus.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/points-minus.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/symm_off.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/qsave.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/qcancel.png
Could not load font because the file does not exist: /usr/share/games/supertuxkart/data/editor/font/font.xml
Could not load mesh, because file could not be opened: : /usr/share/games/supertuxkart/data/editor/icons/indicator.b3d
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/new.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/open.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/save.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/save_as.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/undo.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/redo.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/select.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/move.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/rotate.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/scale.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/delete.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/cam1.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/cam2.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/spline.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/ht.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/music.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/try.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/exit.png
Warning: maps directory doesn't exist. Creating...
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/texture_next.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/texture_previous.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/loading_screen.jpg
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
Could not open file of texture: /usr/share/games/supertuxkart/data/editor/icons/tux.png
![capture du 2016-05-31 13 13 57](https://cloud.githubusercontent.com/assets/417514/15672544/9510290a-2731-11e6-9492-f49afc826547.png)

**Comment by auriamg** [comment]
When you open the editor, it should ask about the directory where STK is installed. Maybe it;s looking in the wrong directory?

**Comment by Boyquotes** [comment]
When I open the editor, I have the textures not found error, when I choose the stk directory on '/usr/share/games/supertuxkart/' I have an another error:

root@debian:/home/nico/stk-editor/build# ./supertuxkart-editor 
Irrlicht Engine version 1.8.1
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
Irrlicht Engine version 1.8.1
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
Using renderer: OpenGL 3.0
Mesa DRI Intel(R) Sandybridge Mobile : Intel Open Source Technology Center
OpenGL driver version is 1.2 or better.
GLSL version: 1.3
Could not create archive for: textures
Could not create archive for: /usr/share/games/supertuxkart/textures
Could not create archive for: /usr/share/games/supertuxkart/textures

**Comment by Boyquotes** [comment]
If I choose the DATA directory, I have this error and STK-editor crash

root@debian:/home/nico/stk-editor/build# ./supertuxkart-editor 
Irrlicht Engine version 1.8.1
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
Irrlicht Engine version 1.8.1
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
Using renderer: OpenGL 3.0
Mesa DRI Intel(R) Sandybridge Mobile : Intel Open Source Technology Center
OpenGL driver version is 1.2 or better.
GLSL version: 1.3
Could not create archive for: textures
Could not create archive for: /usr/share/games/supertuxkart/textures
Could not create archive for: /usr/share/games/supertuxkart/data/editor/xml
Bad news: i couldn't find the xml directory.
Maybe the whole editor folder is missing? :(

**Comment by deveee** [comment]
Do you have STK >= 0.9 in your repositories? The kernel version 3.16.7
suggests that your system is a bit old. STK 0.8.1 doesn't have editor
directory.

Btw. you shouldn't use the '/usr/share/games/supertuxkart/' directory to
avoid write access issues.

The date directory shiould be set to STK data directory.

Maybe try to use stk-editor from our package to see if it works. It should
contain all needed files:
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.1/supertuxkart-0.9.1-linux.tar.xz/download

You can also remove the ".stk-te" directory from your configuration files
and then choose "data" directory from the package above when you run
stk-editor.

**Comment by Boyquotes** [comment]
Ok, Debian 8 provide STK 0.8.2 
ii  supertuxkart                          0.8.1-2+b2                           amd64        3D kart racing game

Works with 0.9.1
Thanks
