### ISSUE TITLE
Track Editor wiki page location?

### ISSUE THREAD

**Issue by vampy** [supertuxkart/stk-editor#19]
I can't seem to find the [track editor wiki page](https://web.archive.org/web/20151004231634/http://supertuxkart.sourceforge.net/Track_Editor) in the [new wiki](https://supertuxkart.net/Community), does anyone have any idea?

**Comment by qwertychouskie** [comment]
https://supertuxkart.net/Track_Editor

**Comment by vampy** [comment]
Right :D, the search on mediawiki works very well /s.
