### ISSUE TITLE
Uh oh getting this Irrlicht related error when compiling

### ISSUE THREAD

**Issue by TheEt1234** [supertuxkart/stk-editor#34]
I am on arch gnu/linux and i am getting the error when compiling: 

```stk-editor/lib/irrlicht/source/Irrlicht/COSOperator.cpp:16:10: fatal error: sys/sysctl.h: No such file or directory```

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/issues/4172

Or you can use https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20210714-linux-64bit.tar.xz, inside it has a stk-editor

**Comment by OPNA2608** [comment]
The issue wasn't solved, `<sys/sysctl.h>` was removed with glibc 2.32. Requesting to have this reopened?

```
[ 39%] Building CXX object lib/irrlicht/CMakeFiles/irrlicht.dir/source/Irrlicht/COSOperator.cpp.o
/build/source/lib/irrlicht/source/Irrlicht/COSOperator.cpp:16:10: fatal error: sys/sysctl.h: No such file or directory
   16 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [lib/irrlicht/CMakeFiles/irrlicht.dir/build.make:1840: lib/irrlicht/CMakeFiles/irrlicht.dir/source/Irrlicht/COSOperator.cpp.o] Error 1
```

**Comment by Benau** [comment]
This editor is not maintained so you can just apply the patch yourself...
