### ISSUE TITLE
provide windows binary

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-editor#42]
Hi

I'm a windows user interested in making new tracks but I'm not a developer and have no idea how to compile it.
I don't know any of the tools and reading the docs on how to compile is like reading Chinese :)

Can you release a windows binary I just need to run? (A zip file that has anything inside)
You can put a link on STK website too.

They way this tool is now offered here, makes it very hard or impossible for non-developers to use it and contribute tracks because we can't do the compiling process.

**Comment by Benau** [comment]
This editor is no longer maintained and please use blender to create track

**Comment by ghost** [comment]
oh no!
Why?
It's much easier with the editor!
